""" 
goal of this script is to ensure each of the methods of the zoidberg MGRID(MagneticField) object,
which I'm developing, behaves identically to the VMEC(MagneticField) object given compatible
equilibria
"""

import numpy as np
from zoidberg.field import MGRID
import matplotlib.pyplot as plt
from zoidberg.plot import plot_poincare, plot_3d_field_line, plot_streamlines
import matplotlib.pyplot as plt
from zoidberg.grid import Grid, rectangular_grid
import dill
from tqdm import tqdm
import argparse

parser = argparse.ArgumentParser()
parser.add_argument('--nx', type=int, default=64,
    help="Grid resolution in the x (radial) direction. Default: 64")
parser.add_argument('--ny', type=int, default=64,
    help="Grid resolution in the y (toroidal) direction. Default: 64")
parser.add_argument('--nz', type=int, default=64,
    help="Grid resolution in the z (poloidal) direction. Default: 64")
parser.add_argument('--vmgrid', type=str, required=True,
    help="Stellopt .mgrid file specifying the vacuum magnetic field")
parser.add_argument('--pmgrid', type=str, required=True,
    help="Stellopt .mgrid file specifying the finite beta magnetic field.\n" \
    "That is, the vmgrid and pmgrid fields should add to the actual field.")
parser.add_argument('--start_R', type=float, required=True,
    help="Location in R (cylindrical coordinates) to begin field line tracing\n" \
    "to determine the geometry of the inner boundary. Tracing begins at y=0.")
parser.add_argument('--start_Z', type=float, required=True,
    help="Location in Z (cylindrical coordinates) to begin field line tracing\n" \
    "to determine the geometry of the inner boundary. Tracing begins at y=0.")



# first, getting vmec to work

wout = "equilibria/wout_G1600-12-89_QA2e-1_Bxdl25_free_L12_M12_N20_s512.nc"

# TODO check against vmec equilibrium -- maybe zoidberg is only compatible with
# an older version of VMEC? in any case this doesn't work

# vmec_field = VMEC(wout) # Doesn't work, using DESC instead

# desc code

import desc

# print("Loading VMEC output into DESC...")
# eq = desc.vmec.VMECIO().load(wout)
# print("Done.")

# print("Plotting 2D cross-section...")
# desc.plotting.plot_section(eq, 'B')
# plt.show()


vacuum_mgrid = "../equilibria/mgrid_G1600-12-89_QA2e-1_Bxdl25-128x128x128_vecpot.nc"
plasma_mgrid = "../equilibria/bmw_G1600-12-89-QA2e-1_Bxdl25_128x128x128.nc"

mgrid = MGRID(vacuum_mgrid, plasma_mgrid)

# # plotting magnetic field from MGRID object

# # # settings for first plot
# # rmin, rmax = 7.5, 10.1
# # zmin, zmax = -3.5, 3.5
# # phi = np.pi

# # settings for fourth plot
# rmin, rmax = 5.5, 9.0
# zmin, zmax = -3.3, 3.3
# phi = np.pi/2

# num_r = 40
# num_z = 55

# Bmin, Bmax = 5.48, 7.5 # for plotting, for comparing to DESC result

# R, Z = np.meshgrid(np.linspace(rmin, rmax, num_r), np.linspace(zmin, zmax, num_z))
# r = R.flatten()
# z = Z.flatten()
# p = phi * np.ones_like(z)

# B = mgrid.Bmag(r, z, p).reshape(num_z, num_r)

# fig = plt.figure(figsize=(4, 5), constrained_layout=True)
# ax = fig.add_subplot()
# cplot = ax.pcolormesh(R, Z, B, cmap="jet", vmin=Bmin, vmax=Bmax)
# fig.colorbar(cplot, label="B")
# ax.set_xlabel("R")
# ax.set_ylabel("Z")
# plt.show()
# # fig.savefig('mod_b_mgrid_2.png', dpi=300)



# plot_poincare(mgrid, 8.4, 0.0, yperiod=np.pi, y_slices=[0], revs=20)

# plot_3d_field_line(vmgrid, 8.3, 3.1, yperiod=np.pi, cycles=3, y_res=100000)

from zoidberg.rzline import circle, line_from_points
from zoidberg.fieldtracer import FieldTracer, trace_poincare
from zoidberg.poloidal_grid import grid_elliptic, grid_annulus
from zoidberg.zoidberg import make_maps, write_maps

#############################################################################
# Define the magnetic field
# Length in y after which the coils return to their starting (R,Z) locations
yperiod = 2*np.pi

magnetic_field = mgrid

# getting outside lines from dill file generated by read_vessel

with open("vessel_rzlines.dill", "rb") as f:
    phi_coords, outer_lines = dill.load(f)

num_original_phi = len(phi_coords)
#############################################################################
# Create the inner flux surface, starting at a point at phi=0
# To do this we need to define the y locations of the poloidal points
# where we will construct grids

start_r = 8.23
start_z = 0.0
start_y = 0.0

nslices = 18
assert len(outer_lines) % nslices == 0

ycoords = np.array([phi_coord for i, phi_coord in enumerate(phi_coords) if ((i % (len(phi_coords) // nslices)) == 0)])

# print("Vessel y coords")
# print(ycoords)

outer_lines = [outer_line for i, outer_line in enumerate(outer_lines) if ((i % (num_original_phi // nslices)) == 0)]

# # for outer_line in outer_lines:
# #     outer_line.plot()

# npoints = 40

# ycoords = np.linspace(0, 2*np.pi, 2*nslices, endpoint=False)


# # Create a field line tracer
# tracer = FieldTracer(magnetic_field)

# # Extend the y coordinates so the tracer loops npoints times around yperiod
# ycoords_all = ycoords
# yperiod = 2*np.pi
# for i in range(1, npoints):
#     ycoords_all = np.append(ycoords_all, ycoords + i * yperiod)

# print(ycoords_all)

# print("Tracing field lines...")
# coord = tracer.follow_field_lines(start_r, start_z, ycoords_all, rtol=1e-20)

# print(coord.shape)

nx = 15 # for making grid
ny = 40

# coord, y_slices = trace_poincare(magnetic_field, start_r, start_z, nplot=2*nslices, yperiod=2*np.pi, revs=40, nover=20)

# # uncomment to make tracings
# coord, y_slices = trace_poincare(magnetic_field, start_r, start_z, y_slices=ycoords, yperiod=2*np.pi)

# inner_lines = []

# for i in range(len(y_slices)):
#     r = coord[:, i, 0, 0]
#     z = coord[:, i, 0, 1]
#     line = line_from_points(r, z)
#     line = line.equallySpaced(n=ny)
#     inner_lines.append(line)


# inner_lines = inner_lines[:len(outer_lines)]

# with open("inner_lines_jun25.dill", "wb") as f:
#     dill.dump(inner_lines, f)

# with open("inner_lines_jun25.dill", "rb") as f:
#     inner_lines = dill.load(f)


# print("Generating grid...")
# pol_slices = [
#     grid_elliptic(inner_line, outer_line, nx, ny, show=False)
#     for inner_line, outer_line in zip(inner_lines, outer_lines)
# ]

# grid = Grid(pol_slices, ycoords, np.pi, yperiodic=True)

# with open("grid_jun25_lr.dill", "wb") as f:
#     dill.dump(grid, f)

with open("grid_jun25.dill", "rb") as f:
    grid = dill.load(f)

# grid.plot3D()

# y_index = 0
# poloidal_grid, y_val = grid.getPoloidalGrid(y_index)
# poloidal_grid.plot()

# maps = make_maps(grid, magnetic_field)
# with open("maps_jun25_lr.dill", "wb") as f:
#     dill.dump(maps, f)

with open("maps_jun25.dill", "rb") as f:
    maps = dill.load(f)

write_maps(grid, magnetic_field, maps, "helios_jul1", metric2d=False)

print("Done.")
